'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterSuccess
    
    '''<summary>
    '''lblGreet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGreet As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserIDshow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserIDshow As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPasswd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPasswd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRePasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRePasswd As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRePasswd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRePasswd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ajaxupdpanelscore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ajaxupdpanelscore As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnFinishRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinishRegister As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As AMKBank.Master
        Get
            Return CType(MyBase.Master,AMKBank.Master)
        End Get
    End Property
End Class
